### PR TITLE
Fix: Newline characters in attribute value came out encoded

### PR DESCRIPTION
**Pull request by mwoc**
I ran into another issue when updating an application to the latest htmlizer version - we had svg elements where the path element's attribute was split over several lines, but was serialized back to containing encoded newline characters, which broke the svg rendering.

I added a test that asserts that the newline and tab characters survive un-encoded, and updated the behaviour of generateAttribute to make that pass.

Also added some more regression tests for the `attr` binding.

### CODE REVIEW

**Comment by mwoc** [comment]
If you agree on the fix and have merged it on, could you then perhaps also release a new version?

**Comment by Munawwar** [comment]
Regarding commit 1 - If attr binding is null, undefined or false, the attribute is removed. It behaves the same as KO in that regard.

**Comment by mwoc** [comment]
Ah in that case - it doesn't seem to remove those attributes currently.
I should learn not to add unrelated commits to PRs:)

**Comment by Munawwar** [comment]
Fixed the issue double escaping of newlines etc. As for attribute not being removed with null/false/undefined, I couldn't replicate it.

**Comment by Munawwar** [comment]
Published v2.2.0.

**Pull request closed without merging**
